server:
  port: 9999

spring:
  application:
    name: ms-assignment
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/cognito-hub}
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    #url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cognito-hub}
    url: jdbc:postgresql://localhost:5432/cognito
    username: ${DB_USERNAME:postgres}
    password: 1234
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: "/"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

keycloak:
  auth-server-url: http://localhost:8080
  credentials:
    secret: xLnnPpvGRBkekbUuVLnnudrkSVDTCzFc
    realm: cognito-hub
security:
  routes:
    - path: /api/v1/assignment
      method: POST
      roles: [CREATE-COURSES]
    - path: /api/v1/assignment/{id}/user/{userId}
      method: PUT
      roles: [VIEW-COURSES]
    - path: /api/v1/assignment/all/{courseId}
      method: GET
      roles: [CREATE-COURSES]


token:
  converter:
    principal-attribute: preferred_username
    resource-id: cognito-hub